<!--
PartCCTV WEB GUI
webgui.phtml
(c) 2016 m1ron0xFF
@license: CC BY-NC-SA 4.0
-->
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PartCCTV WEB GUI</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://yastatic.net/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://yastatic.net/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<script src="https://yastatic.net/jquery/2.2.3/jquery.min.js"></script>
<script src="https://yastatic.net/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<style>
.btn-menu{
   margin-top: 4px;
}
</style>

</head>
<body>

<div class="navbar navbar-default navbar-static-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/"><span>PartCCTV WEB GUI</span></a>
		</div>

		<div class="collapse navbar-collapse" id="navbar-ex-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="/archive/">Архив</a></li>
				<li><a href="https://github.com/mironoff111/PartCCTV/wiki">Документация</a></li>
				<li><a href="#">Выход</a></li>					
			</ul>
		</div>
	</div>
</div>

<div class="section">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="progress progress-striped">
					<div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" style="width: <?=(100-$status['free_space']/$status['total_space']*100)?>%;">На <?=$status['path']?> свободно <?=$status['free_space']?>Гб из <?=$status['total_space']?>Гб</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<a class="btn-menu btn btn-lg btn-success" data-toggle="modal" data-target="#cam_new">Добавить новую камеру</a>
				<a class="btn-menu btn btn-lg btn-info"    data-toggle="modal" data-target="#core_settings">Настройки платформы</a>
				<a class="btn-menu btn btn-lg btn-info"    data-toggle="modal" data-target="#core_users">Пользователи</a>					
				<a class="btn-menu btn btn-lg btn-default" data-toggle="modal" data-target="#core_log">Лог платформы</a>
				<a class="btn-menu btn btn-lg btn-default" data-toggle="modal" data-target="#cam_log">Лог камер</a>			

				<a class="btn-menu btn btn-lg btn-warning" >Частичная перезагрузка платформы</a>	                
				<a class="btn-menu btn btn-lg btn-danger"  >Перезагрузка платформы</a>			
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<hr>
			</div>
<?php
/* if (isset($errors)) {
	foreach ($errors as $key => $value) {
		echo'			
			<div class="col-md-12">
				<div class="alert alert-dismissable alert-danger">
					<b>Критическая ошибка '.$key.' :</b>
					<br>
					'.$value.'
				</div>
			</div>		
		';
	}
	unset($key);
	unset($value);
} */
?>			
		</div>
	</div>
	<div class="container">
		<div class="row">
		
<?php
/* 			while ($cam = $cam_list->fetch_assoc()) {
				if ($cam['enabled'] == 0) {$cam_status = '
						<div class="alert alert-dismissable alert-danger">
							<b>Камера отключена!</b>
				</div>';} else {$cam_status = '';}
				echo'			<div class="col-md-12">
				<div class="panel panel-success">
					<div class="panel-heading">
						<h6 class="panel-title text-warning"><b>'.$cam["title"].' (id'.$cam["id"].')</b></h6>
					</div>
					<div class="panel-body">					
'.$cam_status.'
						<div class="btn-group btn-group-lg">
							<a id="'.$cam["id"].'_ajax" data-toggle="modal" data-target="#cam_settings" class="btn btn-warning">Настройки</a>
							<a href="/archive/id'.$cam["id"].'" class="btn btn-primary">Архив</a>
						</div>
					</div>
				</div>
			</div>';
			}
			unset($cam); */
?>
		</div>
	</div>
</div>

<!-- New Cam Modal -->
<div class="modal fade" id="cam_new" tabindex="-1" role="dialog" aria-labelledby="cam_new">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="cam_new">Новая камера</h4>
      </div>
      <div class="modal-body">
		<form action="" method="post">
		<fieldset>
         
            <div class="control-group">
              <label class="control-label" for="name">Название</label>
              <div class="controls">
                <input type="text" id="name" name="name" required class="form-control input-lg">
              </div>
            </div>
		
            <div class="control-group">
              <label class="control-label" for="source">Источник</label>
              <div class="controls">
                <input type="text" id="source" name="source" required class="form-control input-lg">
              </div>
            </div>
		    <br>
			<input type="hidden" name="action" value="new_cam">
			<input class="btn btn-primary" type="submit" value="Сохранить">
		</fieldset>
		</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
      </div>
    </div>
  </div>
</div>

<!-- Camera Settings Modal -->
<div class="modal fade" id="cam_settings" tabindex="-1" role="dialog" aria-labelledby="cam_settings">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="cam_settings">Настройки камеры</h4>
      </div>
      <div class="modal-body">
		<form action="" method="post">
		<fieldset>
            <div class="control-group">
              <label class="control-label" for="id">ID</label>
              <div class="controls">
                <input type="text" id="id" name="id" required class="form-control input-lg">
              </div>
            </div>
         
            <div class="control-group">
              <label class="control-label" for="name">Название</label>
              <div class="controls">
                <input type="text" id="name" name="name" required class="form-control input-lg">
              </div>
            </div>
		
            <div class="control-group">
              <label class="control-label" for="source">Источник</label>
              <div class="controls">
                <input type="text" id="source" name="source" required class="form-control input-lg">
              </div>
            </div>
		
			<div class="checkbox">
				<label>
				<input type="checkbox"> Камера включена
				</label>
			</div>
		
			<input class="btn btn-primary" type="submit" value="Сохранить">
		</fieldset>
		</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Удалить камеру</button>	  
        <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
      </div>
    </div>
  </div>
</div>

<!-- Settings Modal -->
<div class="modal fade" id="core_settings" tabindex="-1" role="dialog" aria-labelledby="core_settings">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="core_settings">Настройки платформы</h4>
      </div>
      <div class="modal-body">
		<form action="" method="post">
		<fieldset>
<?php
/* 			while ($option = $settings->fetch_assoc()) {
				echo'            <div class="control-group">
              <label class="control-label" for="'.$option["param"].'">'.$option["param"].'</label>
              <div class="controls">
                <input type="text" id="'.$option["param"].'" name="'.$option["param"].'" value="'.$option["value"].'" required class="form-control input-lg">
              </div>
            </div>';
			}
			unset($option); */
?>
			<br>
			<input type="hidden" name="action" value="platform_settings">
			<input class="btn btn-primary" type="submit" value="Сохранить">

		</fieldset>
		</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
      </div>
    </div>
  </div>
</div>

<!-- Users Modal -->
<div class="modal fade" id="core_users" tabindex="-1" role="dialog" aria-labelledby="core_users">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="core_users">Пользователи</h4>
      </div>
      <div class="modal-body">
		<pre id="core_log_ajax"></pre>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

<!-- Core Log Modal -->
<div class="modal fade" id="core_log" tabindex="-1" role="dialog" aria-labelledby="core_log">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="core_log">Лог платформы</h4>
      </div>
      <div class="modal-body">
		<pre id="core_log_ajax"></pre>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

<!-- Camera Log Modal -->
<div class="modal fade" id="cam_log" tabindex="-1" role="dialog" aria-labelledby="cam_log">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="cam_log">Лог камер</h4>
      </div>
      <div class="modal-body">
		<pre id="cam_log_ajax"></pre>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

<!-- Core Log Modal -->
<script>
$("#core_log").on("show.bs.modal", function(e) {
$.ajax({type: "GET", url: "/api/1.0/platform/log", 
    dataType:"text", timeout:30000, async:true,
    error: function(xhr) {
        console.log('Ошибка!'+xhr.status+' '+xhr.statusText); 
    },
    success: function(a) {
        document.getElementById("core_log_ajax").innerHTML=a;
    }  
})});
</script>

<!-- Cam Log Modal -->
<script>
$("#cam_log").on("show.bs.modal", function(e) {
$.ajax({type: "GET", url: "/api/1.0/camera/log", 
    dataType:"text", timeout:30000, async:true,
    error: function(xhr) {
        console.log('Ошибка!'+xhr.status+' '+xhr.statusText); 
    },
    success: function(a) {
        document.getElementById("cam_log_ajax").innerHTML=a;
    }  
})});
</script>

</body>
</html>
