<!--
PartCCTV WEB GUI
webgui.phtml
(c) 2016 m1ron0xFF
@license: CC BY-NC-SA 4.0
-->
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PartCCTV WEB GUI</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://yastatic.net/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://yastatic.net/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<script src="https://yastatic.net/jquery/2.2.3/jquery.min.js"></script>
<script src="https://yastatic.net/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<style>
.btn-menu{
   margin-top: 4px;
}
</style>

</head>

<body>
<div class="navbar navbar-default navbar-static-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/"><span>PartCCTV WEB GUI</span></a>
            <p class="navbar-text" id="core_pid"></p>
		</div>

		<div class="collapse navbar-collapse" id="navbar-ex-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="/archive/">Архив</a></li>
				<li><a href="https://github.com/mironoff111/PartCCTV/wiki">Документация</a></li>
				<li><a href="#">Выход</a></li>					
			</ul>
		</div>
	</div>
</div>

<div class="section">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="progress progress-striped" id="core_status_ajax">
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<a class="btn-menu btn btn-lg btn-success" data-toggle="modal" data-target="#cam_new">Добавить новую камеру</a>
				<a class="btn-menu btn btn-lg btn-info"    data-toggle="modal" data-target="#core_settings">Настройки платформы</a>
				<a class="btn-menu btn btn-lg btn-info"    data-toggle="modal" data-target="#core_users">Пользователи</a>					
				<a class="btn-menu btn btn-lg btn-default" data-toggle="modal" data-target="#core_log">Лог платформы</a>
				<a class="btn-menu btn btn-lg btn-default" data-toggle="modal" data-target="#cam_log">Лог камер</a>			

				<a class="btn-menu btn btn-lg btn-warning" >Частичная перезагрузка платформы</a>	                
				<a class="btn-menu btn btn-lg btn-danger"  >Перезагрузка платформы</a>			
			</div>
		</div>
        
        <div class="col-md-12">
            <hr>
        </div>

	</div>
	<div class="container">
		<div class="row" id="cam_list_ajax">
		</div>
	</div>
</div>

<!-- New Cam Modal -->
<div class="modal fade" id="cam_new" tabindex="-1" role="dialog" aria-labelledby="cam_new">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="cam_new">Новая камера</h4>
      </div>
      <div class="modal-body">
		<form action="" method="post">
		<fieldset>
        
            <div class="control-group">
              <label class="control-label" for="name">Название</label>
              <div class="controls">
                <input type="text" id="name" name="name" required class="form-control input-lg">
              </div>
            </div>
		
            <div class="control-group">
              <label class="control-label" for="source">Источник</label>
              <div class="controls">
                <input type="text" id="source" name="source" required class="form-control input-lg">
              </div>
            </div>
            
		    <br>
            
			<input class="btn btn-primary" type="submit" value="Сохранить">
            
		</fieldset>
		</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
      </div>
    </div>
  </div>
</div>

<!-- Camera Settings Modal -->
<div class="modal fade" id="cam_settings" tabindex="-1" role="dialog" aria-labelledby="cam_settings">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="cam_settings">Настройки камеры</h4>
      </div>
      <div class="modal-body">
		<form action="" method="post">
		<fieldset>
            <div class="control-group">
              <label class="control-label" for="id">ID</label>
              <div class="controls">
                <input type="text" id="id" name="id" required class="form-control input-lg">
              </div>
            </div>
         
            <div class="control-group">
              <label class="control-label" for="name">Название</label>
              <div class="controls">
                <input type="text" id="name" name="name" required class="form-control input-lg">
              </div>
            </div>
		
            <div class="control-group">
              <label class="control-label" for="source">Источник</label>
              <div class="controls">
                <input type="text" id="source" name="source" required class="form-control input-lg">
              </div>
            </div>
		
			<div class="checkbox">
				<label>
				<input type="checkbox"> Камера включена
				</label>
			</div>
		
			<input class="btn btn-primary" type="submit" value="Сохранить">
		</fieldset>
		</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Удалить камеру</button>	  
        <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
      </div>
    </div>
  </div>
</div>

<!-- Settings Modal -->
<div class="modal fade" id="core_settings" tabindex="-1" role="dialog" aria-labelledby="core_settings">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="core_settings">Настройки платформы</h4>
      </div>
      <div class="modal-body" id="core_settings_ajax">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
      </div>
    </div>
  </div>
</div>

<!-- Users Modal -->
<div class="modal fade" id="core_users" tabindex="-1" role="dialog" aria-labelledby="core_users">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="core_users">Пользователи</h4>
      </div>
      <div class="modal-body">
        <!-- TBD -->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

<!-- Core Log Modal -->
<div class="modal fade" id="core_log" tabindex="-1" role="dialog" aria-labelledby="core_log">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="core_log">Лог платформы</h4>
      </div>
      <div class="modal-body">
		<pre id="core_log_ajax"></pre>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

<!-- Camera Log Modal -->
<div class="modal fade" id="cam_log" tabindex="-1" role="dialog" aria-labelledby="cam_log">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="cam_log">Лог камер</h4>
      </div>
      <div class="modal-body">
		<pre id="cam_log_ajax"></pre>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

<script>
$(function() {
// Progress Bar & Core Status
$.ajax({
    url: '/api/1.0/platform/status',
    type: "get",
    dataType: "json",
    cache: true,
    success: function(data) {
        var pbar = '<div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" style="width: '+ (data.total_space - data.free_space)/data.total_space*100 +'%;">На '+data.path+' свободно '+data.free_space+'Гб из '+data.total_space+'Гб</div>';
        $('#core_status_ajax').html(pbar);
        $('#core_pid').html('Core PID: '+ data.core_pid);
    }
});

// Cam List
$.ajax({
    url: '/api/1.0/camera/list',
    type: "get",
    dataType: "json",
    cache: true,
    success: function(data) {
        drawCamList(data);
    }
});

function drawCamList(data) {

    var html = '';

    for (var i = 0; i < data.length; i++) {
        html += drawCamListRaw(data[i]);
    }

    $('#cam_list_ajax').html(html);
}

function drawCamListRaw(rawData) {

    if (rawData.enabled==0) {
        var error = '<div class="alert alert-warning">' +
                        '<b>Камера отключена!</b>' +
                    '</div>';
    } else if (rawData.enabled==1 && !rawData.pid ) {
        var error = '<div class="alert alert-danger">' +
                        '<b>Воркер не запущен, запись не производится!</b>' +
                    '</div>';    
    } else {
        var error = '';
    }

    return '<div class="col-md-12">' +
        '<div class="panel panel-success">' +
            '<div class="panel-heading">' +
                '<h6 class="panel-title text-warning"><b>'+rawData.title+' (id'+rawData.id+')</b> <kbd>PID '+rawData.pid+'</kbd></h6>' +
            '</div>' +
            '<div class="panel-body">' +
                error +
                '<div class="btn-group btn-group-lg">' +
                    '<a data-toggle="modal" data-target="#cam_settings" class="btn btn-warning">Настройки</a>' +
                    '<a href="/archive/id'+rawData.id+'" class="btn btn-primary">Архив</a>' +
                '</div>' +
            '</div>' +
        '</div>' +
    '</div>';          
}

// Core Settings Modal
$("#core_settings").on("show.bs.modal", function() {
$.ajax({
    url: '/api/1.0/platform/settings',
    type: "get",
    dataType: "json",
    cache: true,
    success: function(data) {
        drawSettingsModal(data);
    }
});

function drawSettingsModal(data) {
    //часть формы до полей, которые генерируем автоматически
    var html = '<form action="" method="post">' +
            '<fieldset>';

    //генерируем html-код полей с именами и значениями из поступивших данных 
    for (var i = 0; i < data.length; i++) {
        html += drawSettingsRaw(data[i]);
    }

    //часть формы после генерируемых полей
    html += '<input type="hidden" name="action" value="platform_settings">' +
        '<br>' +
        '<input class="btn btn-primary" type="submit" value="Сохранить">' +
        '</fieldset>' +
    '</form>';
    
    $('#core_settings_ajax').html(html);
}

function drawSettingsRaw(rawData) {
    return '<div class="control-group">' +
        '<label class="control-label" for="'+rawData.param+'">'+rawData.param+'</label>' +
        '<div class="controls">' +
            '<input type="text" id="'+rawData.param+'" name="'+rawData.param+'" value="'+rawData.value+'"  required class="form-control input-lg">' +
        '</div>' +
    '</div>';
}
});

// Core Log Modal
$("#core_log").on("show.bs.modal", function() {
$.ajax({
    type: "get", 
    url: "/api/1.0/platform/log", 
    dataType:"text", 
    cache: true,
    error: function(xhr) {
        console.log('Ошибка!'+xhr.status+' '+xhr.statusText); 
    },
    success: function(a) {
        $('#core_log_ajax').html(a);
    }  
})});

// Cam Log Modal
$("#cam_log").on("show.bs.modal", function() {
$.ajax({
    type: "get", 
    url: "/api/1.0/camera/log", 
    dataType:"text", 
    cache: true,
    error: function(xhr) {
        console.log('Ошибка!'+xhr.status+' '+xhr.statusText); 
    },
    success: function(a) {
        $('#cam_log_ajax').html(a);
    }  
})});
});
</script>

</body>
</html>
